# Generated by Django 4.1.7 on 2023-04-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_forumtopic_forumsectiontopic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmessage',
            old_name='author',
            new_name='user',
        ),
    ]
