# Generated by Django 3.2.18 on 2023-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_author_topicmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsection',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Короткое название раздела'),
        ),
        migrations.AddField(
            model_name='forumsectiontopic',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Короткое название темы внутри раздела'),
        ),
    ]
