# Generated by Django 3.2.18 on 2023-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20230406_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsection',
            name='slug',
            field=models.SlugField(verbose_name='Короткое название раздела'),
        ),
        migrations.AlterField(
            model_name='forumsectiontopic',
            name='slug',
            field=models.SlugField(verbose_name='Короткое название темы внутри раздела'),
        ),
    ]
