# Generated by Django 3.2.18 on 2023-04-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20230410_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsection',
            name='number_of_topics',
        ),
        migrations.RemoveField(
            model_name='forumsectiontopic',
            name='number_of_messages',
        ),
    ]
