# Generated by Django 4.1.7 on 2023-04-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedAdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя/Название')),
                ('city', models.CharField(choices=[('Москва', 'Москва'), ('Владивосток', 'Владивосток'), ('Тюмень', 'Тюмень')], max_length=11, verbose_name='Город')),
                ('style', models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Jazz', 'Jazz')], max_length=5, verbose_name='Стиль музыки')),
                ('instruments', models.CharField(choices=[('Vocal', 'Vocal'), ('Guitar', 'Guitar'), ('Piano', 'Piano')], max_length=6, verbose_name='Инструменты')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number_of_members', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
