# Generated by Django 4.1.7 on 2023-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedadv',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя музыканта'),
        ),
    ]
