# Generated by Django 3.2.18 on 2023-04-13 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_alter_feedadv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_matches', to=settings.AUTH_USER_MODEL, verbose_name='На кого откликнулись')),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_matches', to=settings.AUTH_USER_MODEL, verbose_name='Кто откликнулся')),
            ],
        ),
    ]
