# Generated by Django 3.2.18 on 2023-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='number_of_messages',
            field=models.IntegerField(default=0, verbose_name='Количество сообщений'),
        ),
    ]
