# Generated by Django 3.2.18 on 2023-04-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_alter_dialog_number_of_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='number_of_messages',
        ),
    ]
